# Don't print a new line at the start of the prompt
add_newline = true

# The r/unixporn "Pill" layout with Live Time added
format = """
$username$directory$time$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[╰─](bold fg:#7aa2f7) "
error_symbol = "[╰─](bold fg:#f7768e) "

[username]
show_always = true
style_user = "bg:#283457 fg:#7aa2f7 bold"
style_root = "bg:#283457 fg:#f7768e bold"
# Added the closing curve [] and a space to the end of this format string
format = "[╭─](bold fg:#283457)[󰭹 $user]($style)[](bold fg:#283457) "

[hostname]
# Disabled the hostname so "anshu" stops printing a second time
disabled = true

[directory]
home_symbol = " "
read_only = " "
style = "bg:#15161e fg:#c0caf5 bold"
truncation_length = 3
truncation_symbol = "••/"
format = "[](bold fg:#15161e)[$path]($style)[](bold fg:#15161e) "

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈 "
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[git_branch]
symbol = "󰘬 "
style = "bg:#7dcfff fg:#1a1b26 bold"
format = "[](bold fg:#7dcfff)[$symbol$branch]($style)[](bold fg:#7dcfff) "

[git_status]
style = "bg:#f7768e fg:#1a1b26 bold"
format = "[](bold fg:#f7768e)[$all_status$ahead_behind]($style)[](bold fg:#f7768e) "
# Simplified, universally understood status icons:
conflicted = "!! "
ahead = "↑ "
behind = "↓ "
diverged = "↕ "
untracked = "? "
stashed = "S "
modified = "! "
staged = "+ "
renamed = "» "
deleted = "x "

[cmd_duration]
min_time = 500
style = "bg:#e0af68 fg:#1a1b26 bold"
format = "[](bold fg:#e0af68)[󰪢 $duration]($style)[](bold fg:#e0af68)"

[package]
disabled = true