add_newline = true

format = """
$username$directory$time$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[╰─](bold fg:#88c0d0) "
error_symbol = "[╰─](bold fg:#bf616a) "

[username]
show_always = true
style_user = "bg:#434c5e fg:#88c0d0 bold"
style_root = "bg:#434c5e fg:#bf616a bold"
format = "[╭─](bold fg:#434c5e)[󰭹 $user]($style)[](bold fg:#434c5e) "

[hostname]
disabled = true

[directory]
home_symbol = " "
read_only = " "
style = "bg:#2e3440 fg:#eceff4 bold"
truncation_length = 3
truncation_symbol = "••/"
format = "[](bold fg:#2e3440)[$path]($style)[](bold fg:#2e3440) "

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈 "
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[git_branch]
symbol = " "
style = "bg:#434c5e fg:#a3be8c bold"
format = "[](bold fg:#434c5e)[$symbol$branch]($style)[](bold fg:#434c5e) "

[git_status]
style = "bg:#434c5e fg:#ebcb8b bold"
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#2e3440 fg:#81a1c1 bold"
format = "[](bold fg:#2e3440)[󱑎 $time]($style)[](bold fg:#2e3440) "

[cmd_duration]
min_time = 2_000
style = "bg:#434c5e fg:#b48ead bold"
format = "[](bold fg:#434c5e)[󱐋 $duration]($style)[](bold fg:#434c5e) "
