add_newline = true

format = """
$username$directory$time$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[╰─](bold fg:#7d9726) "
error_symbol = "[╰─](bold fg:#ba6236) "

[username]
show_always = true
style_user = "bg:#303c3b fg:#7d9726 bold"
style_root = "bg:#303c3b fg:#ba6236 bold"
format = "[╭─](bold fg:#303c3b)[󰭹 $user]($style)[](bold fg:#303c3b) "

[hostname]
disabled = true

[directory]
home_symbol = " "
read_only = " "
style = "bg:#1f2927 fg:#e7e6df bold"
truncation_length = 3
truncation_symbol = "••/"
format = "[](bold fg:#1f2927)[$path]($style)[](bold fg:#1f2927) "

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈 "
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[git_branch]
symbol = " "
style = "bg:#303c3b fg:#7d9726 bold"
format = "[](bold fg:#303c3b)[$symbol$branch]($style)[](bold fg:#303c3b) "

[git_status]
style = "bg:#303c3b fg:#a5980d bold"
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#1f2927 fg:#a5980d bold"
format = "[](bold fg:#1f2927)[󱑎 $time]($style)[](bold fg:#1f2927) "

[cmd_duration]
min_time = 2_000
style = "bg:#303c3b fg:#5f9182 bold"
format = "[](bold fg:#303c3b)[󱐋 $duration]($style)[](bold fg:#303c3b) "
