add_newline = true

format = """
$username$directory$time$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[╰─](bold fg:#ff9248) "
error_symbol = "[╰─](bold fg:#cf5d44) "

[username]
show_always = true
style_user = "bg:#452c22 fg:#ff9248 bold"
style_root = "bg:#452c22 fg:#cf5d44 bold"
format = "[╭─](bold fg:#452c22)[󰭹 $user]($style)[](bold fg:#452c22) "

[hostname]
disabled = true

[directory]
home_symbol = " "
read_only = " "
style = "bg:#291e1a fg:#e8dcd5 bold"
truncation_length = 3
truncation_symbol = "••/"
format = "[](bold fg:#291e1a)[$path]($style)[](bold fg:#291e1a) "

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈 "
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[git_branch]
symbol = " "
style = "bg:#452c22 fg:#9fb865 bold"
format = "[](bold fg:#452c22)[$symbol$branch]($style)[](bold fg:#452c22) "

[git_status]
style = "bg:#452c22 fg:#f7bb63 bold"
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#291e1a fg:#f7bb63 bold"
format = "[](bold fg:#291e1a)[󱑎 $time]($style)[](bold fg:#291e1a) "

[cmd_duration]
min_time = 2_000
style = "bg:#452c22 fg:#d49a7a bold"
format = "[](bold fg:#452c22)[󱐋 $duration]($style)[](bold fg:#452c22) "
