add_newline = true

format = """
$username$directory$time$git_branch$git_status$cmd_duration
$character"""

[character]
success_symbol = "[╰─](bold fg:#ba68c8) "
error_symbol = "[╰─](bold fg:#ff5252) "

[username]
show_always = true
style_user = "bg:#483266 fg:#ba68c8 bold"
style_root = "bg:#483266 fg:#ff5252 bold"
format = "[╭─](bold fg:#483266)[󰭹 $user]($style)[](bold fg:#483266) "

[hostname]
disabled = true

[directory]
home_symbol = " "
read_only = " "
style = "bg:#241c33 fg:#ede7f6 bold"
truncation_length = 3
truncation_symbol = "••/"
format = "[](bold fg:#241c33)[$path]($style)[](bold fg:#241c33) "

[directory.substitutions]
"Desktop" = " "
"Documents" = " "
"Downloads" = " "
"Music" = "󰎈 "
"Pictures" = " "
"Videos" = " "
"GitHub" = "󰊤 "

[git_branch]
symbol = " "
style = "bg:#483266 fg:#81c784 bold"
format = "[](bold fg:#483266)[$symbol$branch]($style)[](bold fg:#483266) "

[git_status]
style = "bg:#483266 fg:#ffd740 bold"
format = "[$all_status$ahead_behind]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#241c33 fg:#ce93d8 bold"
format = "[](bold fg:#241c33)[󱑎 $time]($style)[](bold fg:#241c33) "

[cmd_duration]
min_time = 2_000
style = "bg:#483266 fg:#7aa2f7 bold"
format = "[](bold fg:#483266)[󱐋 $duration]($style)[](bold fg:#483266) "
