#!/usr/bin/env bash
# ==============================================================================
# Ballade Joplin Dynamic Themer & Catppuccin-Grade Theme Engine
# Designed with a 3-tier depth architecture (Crust -> Mantle -> Base)
# ==============================================================================

THEME_KEY="${1:-green}"
JOPLIN_DIR="$HOME/.config/joplin-desktop"
[ ! -d "$JOPLIN_DIR" ] && mkdir -p "$JOPLIN_DIR"

case "$THEME_KEY" in
    green|atelier|everforest)
        ACCENT_HEX="#7D9726"
        ACCENT_HOVER="#93AE38"
        ACCENT_MUTED="#5B9D48"
        BG_BASE="#141C1A"
        BG_MANTLE="#101715"
        BG_CRUST="#0B100E"
        SURFACE0="#1A2421"
        SURFACE1="#22302C"
        SURFACE2="#2C3E38"
        FG_TEXT="#E0E6E2"
        FG_SUBTEXT="#A2ADA6"
        FG_OVERLAY="#64726A"
        ;;
    golden|gold|amber|yellow)
        ACCENT_HEX="#F0B849"
        ACCENT_HOVER="#FED268"
        ACCENT_MUTED="#D49B2C"
        BG_BASE="#1A150D"
        BG_MANTLE="#151009"
        BG_CRUST="#0F0B06"
        SURFACE0="#221C12"
        SURFACE1="#2D2518"
        SURFACE2="#3B3120"
        FG_TEXT="#EBE4D5"
        FG_SUBTEXT="#ADA594"
        FG_OVERLAY="#6E6657"
        ;;
    orange|sunset|tangerine)
        ACCENT_HEX="#FF9248"
        ACCENT_HOVER="#FFB480"
        ACCENT_MUTED="#E0762F"
        BG_BASE="#1A120D"
        BG_MANTLE="#150D09"
        BG_CRUST="#0F0906"
        SURFACE0="#241912"
        SURFACE1="#302118"
        SURFACE2="#3E2B20"
        FG_TEXT="#EDE2DB"
        FG_SUBTEXT="#AEA29A"
        FG_OVERLAY="#6E625A"
        ;;
    pink|sakura)
        ACCENT_HEX="#D4659A"
        ACCENT_HOVER="#F298C4"
        ACCENT_MUTED="#B84E80"
        BG_BASE="#1A0F17"
        BG_MANTLE="#150B12"
        BG_CRUST="#0F080C"
        SURFACE0="#241520"
        SURFACE1="#301C2B"
        SURFACE2="#3E2437"
        FG_TEXT="#EFE0E8"
        FG_SUBTEXT="#AFA0A8"
        FG_OVERLAY="#6E6068"
        ;;
    purple|amethyst)
        ACCENT_HEX="#9C5ADB"
        ACCENT_HOVER="#BA68C8"
        ACCENT_MUTED="#7B3EA6"
        BG_BASE="#140E1C"
        BG_MANTLE="#0F0A16"
        BG_CRUST="#0A070F"
        SURFACE0="#1C1427"
        SURFACE1="#261B35"
        SURFACE2="#322446"
        FG_TEXT="#E7E0EF"
        FG_SUBTEXT="#A7A0AF"
        FG_OVERLAY="#696071"
        ;;
    red|crimson)
        ACCENT_HEX="#BF3F43"
        ACCENT_HOVER="#E55353"
        ACCENT_MUTED="#A32E32"
        BG_BASE="#1A0E10"
        BG_MANTLE="#150A0C"
        BG_CRUST="#0F0708"
        SURFACE0="#241416"
        SURFACE1="#301B1E"
        SURFACE2="#3E2326"
        FG_TEXT="#EFE0E1"
        FG_SUBTEXT="#AFA0A1"
        FG_OVERLAY="#6E5F61"
        ;;
    blue|tokyo_night|tokyonight)
        ACCENT_HEX="#7AA2F7"
        ACCENT_HOVER="#89B4FA"
        ACCENT_MUTED="#5C7EB5"
        BG_BASE="#11121A"
        BG_MANTLE="#0D0E15"
        BG_CRUST="#090A0E"
        SURFACE0="#181924"
        SURFACE1="#202230"
        SURFACE2="#2A2C3E"
        FG_TEXT="#E0E4F0"
        FG_SUBTEXT="#A0A5B5"
        FG_OVERLAY="#5E6476"
        ;;
    grayscale|nord|monochrome|bw)
        ACCENT_HEX="#88C0D0"
        ACCENT_HOVER="#81A1C1"
        ACCENT_MUTED="#5E81AC"
        BG_BASE="#1A1D24"
        BG_MANTLE="#14171D"
        BG_CRUST="#0E1014"
        SURFACE0="#232730"
        SURFACE1="#2E333F"
        SURFACE2="#3B4252"
        FG_TEXT="#E5E9F0"
        FG_SUBTEXT="#A5A9B5"
        FG_OVERLAY="#646A78"
        ;;
    *)
        ACCENT_HEX="#7D9726"
        ACCENT_HOVER="#93AE38"
        ACCENT_MUTED="#5B9D48"
        BG_BASE="#141C1A"
        BG_MANTLE="#101715"
        BG_CRUST="#0B100E"
        SURFACE0="#1A2421"
        SURFACE1="#22302C"
        SURFACE2="#2C3E38"
        FG_TEXT="#E0E6E2"
        FG_SUBTEXT="#A2ADA6"
        FG_OVERLAY="#64726A"
        ;;
esac

# 1. userchrome.css (UI Layout, Sidebars, Editor, Toolbars, Modals)
cat << EOF_CHROME > "$JOPLIN_DIR/userchrome.css"
/* ==========================================================================
   Ballade Catppuccin-Grade Theme for Joplin (UI)
   Auto-generated by Ballade Multi-Theme Orchestrator ($THEME_KEY)
   ========================================================================== */

:root {
    --theme-accent: $ACCENT_HEX;
    --theme-accent-hover: $ACCENT_HOVER;
    --theme-accent-muted: $ACCENT_MUTED;
    --theme-base: $BG_BASE;
    --theme-mantle: $BG_MANTLE;
    --theme-crust: $BG_CRUST;
    --theme-surface0: $SURFACE0;
    --theme-surface1: $SURFACE1;
    --theme-surface2: $SURFACE2;
    --theme-text: $FG_TEXT;
    --theme-subtext: $FG_SUBTEXT;
    --theme-overlay: $FG_OVERLAY;
    --theme-border: rgba(255, 255, 255, 0.08);
}

/* Base App Canvas - ALL panels */
html, body, #react-root, .root-content, .rli-root, .main-screen,
div[class*="mainScreen"], div[class*="MainScreen"] {
    background-color: var(--theme-base) !important;
    color: var(--theme-text) !important;
}

/* Cover every resizable panel and their children */
.resizableLayoutItem, .resizableLayoutItem > div,
div[class*="resizable"], div[class*="Resizable"],
div[class*="pane"], div[class*="Pane"],
div[class*="panel"], div[class*="Panel"] {
    background-color: var(--theme-base) !important;
}

/* Note list column header strip - the bar above New Note buttons */
div[class*="noteList"] > div,
div[class*="NoteList"] > div {
    background-color: var(--theme-mantle) !important;
}

/* Fix ALL SVG icons - Joplin hardcodes blue/gray fill on svg paths */
button svg, button svg path, button svg circle,
div[class*="toolbar"] svg, div[class*="Toolbar"] svg path,
div[class*="topBar"] svg path, div[class*="TopBar"] svg path {
    color: var(--theme-subtext) !important;
    fill: var(--theme-subtext) !important;
}
button:hover svg path,
div[class*="toolbar"] button:hover svg path,
div[class*="topBar"] button:hover svg path {
    color: var(--theme-accent) !important;
    fill: var(--theme-accent) !important;
}

/* Scrollbars */
::-webkit-scrollbar {
    width: 8px !important;
    height: 8px !important;
}
::-webkit-scrollbar-track {
    background: var(--theme-crust) !important;
}
::-webkit-scrollbar-thumb {
    background-color: var(--theme-surface1) !important;
    border-radius: 4px !important;
}
::-webkit-scrollbar-thumb:hover {
    background-color: var(--theme-accent) !important;
}

/*********************************************************************************
 * 1. SIDEBAR & NOTEBOOKS (CRUST LAYER)
 *********************************************************************************/
.sidebar, .side-bar, .rli-sidebar, div[class*="sideBar"], div[class*="sidebar"] {
    background-color: var(--theme-crust) !important;
    border-right: 1px solid var(--theme-border) !important;
}

/* Folders & Tags */
.folders .list-item-container, .tags .list-item-container,
.side-bar .list-item, .folders .list-item, .tags .list-item {
    background-color: var(--theme-crust) !important;
    color: var(--theme-subtext) !important;
    border: none !important;
}

.folders .list-item-container a, .tags .list-item-container a,
.side-bar a, .folders a, .tags a {
    color: var(--theme-subtext) !important;
}

.folders .list-item-container:hover, .tags .list-item-container:hover,
.side-bar .list-item:hover, .folders a:hover, .tags a:hover {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-text) !important;
}

.side-bar .list-item.selected, .folders .selected, .tags .selected,
.side-bar .folder-and-tag-item.selected {
    background-color: var(--theme-surface1) !important;
    color: var(--theme-accent) !important;
    border-left: 3px solid var(--theme-accent) !important;
}

.side-bar .header, .side-bar .title, .sidebar-header, .sidebar-title {
    color: var(--theme-accent) !important;
    font-weight: 700 !important;
    text-transform: uppercase !important;
    font-size: 11px !important;
    letter-spacing: 1px !important;
}

/* Synchronize Button at bottom of sidebar */
.sidebar > div:last-of-type, .sidebar-footer, .side-bar .synchronize-button {
    background-color: var(--theme-crust) !important;
    border-top: 1px solid var(--theme-border) !important;
}

.sidebar > div:last-of-type > button, .synchronize-button button, .synchronize-button {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-accent) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 6px !important;
}
.sidebar > div:last-of-type > button:hover, .synchronize-button button:hover {
    background-color: var(--theme-surface1) !important;
}

/*********************************************************************************
 * 2. NOTE LIST PANEL (MANTLE LAYER)
 *********************************************************************************/
.note-list, .rli-note-list, div[class*="noteList"], .item-list.note-list,
.cLdGCO, .cLdGCO > div {
    background-color: var(--theme-mantle) !important;
    border-right: 1px solid var(--theme-border) !important;
}

/* Search bar inside note list */
.search-bar, .note-list-search, div[height="50"], div[class*="searchBar"] {
    background-color: var(--theme-mantle) !important;
    border-bottom: 1px solid var(--theme-border) !important;
}

.search-bar input, .note-search-bar input, div[height="50"] input,
input[type="search"], div[class*="search"] input {
    background-color: var(--theme-crust) !important;
    border: 1px solid var(--theme-border) !important;
    color: var(--theme-text) !important;
    border-radius: 6px !important;
    padding: 6px 10px !important;
}

.search-bar input:focus, input[type="search"]:focus {
    border-color: var(--theme-accent) !important;
    outline: none !important;
}

/* Action Buttons (+ note, + to-do) */
.new-note-todo-buttons > button, .new-note-button, .new-todo-button,
.header-button.primary {
    background-color: var(--theme-accent) !important;
    color: #000000 !important;
    border: none !important;
    border-radius: 6px !important;
    font-weight: 700 !important;
}
.new-note-todo-buttons > button:hover, .new-note-button:hover, .new-todo-button:hover {
    background-color: var(--theme-accent-hover) !important;
}
.new-todo-button > span, .new-note-button > span {
    color: #000000 !important;
    font-weight: 700 !important;
}

/* List Items */
.note-list .list-item-container, .note-list-item, .list-item-wrapper {
    background-color: var(--theme-mantle) !important;
    border-bottom: 1px solid rgba(255, 255, 255, 0.03) !important;
}

.note-list .list-item-container a, .note-list-item a {
    color: var(--theme-text) !important;
}

.note-list .list-item-container:hover, .note-list-item:hover,
.list-item-wrapper.-highlight-on-hover:hover {
    background-color: var(--theme-surface0) !important;
}

/* Selected Note Item */
.list-item-wrapper.-selected, .note-list-item > .content.-selected,
.note-list .list-item.selected, .rli-note-list-item.selected {
    background-color: var(--theme-surface1) !important;
    border-left: 3px solid var(--theme-accent) !important;
}
.list-item-wrapper.-selected a, .note-list-item > .content.-selected .title,
.note-list .list-item.selected .title {
    color: var(--theme-accent) !important;
    font-weight: 700 !important;
}

/*********************************************************************************
 * 3. TOP BAR, NOTE TITLE & EDITOR (BASE LAYER)
 *********************************************************************************/
.header, .header-inner, header, .top-bar, .menubar, .menu-bar, .title-bar,
div[class*="header"], div[class*="Header"], div[class*="topBar"], .rli-header,
.note-header, div[class*="noteHeader"] {
    background-color: var(--theme-base) !important;
    border-bottom: 1px solid var(--theme-border) !important;
    color: var(--theme-text) !important;
}

/* Note Title Input */
.title-input, .rli-editor .cCOtNv > input, input.title-input,
div[class*="titleInput"] input, div[class*="noteHeader"] input {
    background-color: var(--theme-base) !important;
    color: var(--theme-accent) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 6px !important;
    font-weight: 700 !important;
}
.title-input:focus {
    border-color: var(--theme-accent) !important;
}

/* Editor Toolbar */
.editor-toolbar {
    background-color: var(--theme-base) !important;
    border-bottom: 1px solid var(--theme-border) !important;
}

.editor-toolbar button, .editor-toolbar a, .header button, button {
    background-color: transparent !important;
    border: none !important;
    color: var(--theme-subtext) !important;
    border-radius: 4px !important;
}
.editor-toolbar button:hover, .editor-toolbar a:hover, .header button:hover, button:hover {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-accent) !important;
}

/* CodeMirror Editor */
.rli-editor, .cm-editor, .CodeMirror, .CodeMirror-lines,
.cm-s-material-darker.CodeMirror, div[class*="editor"] {
    background-color: var(--theme-base) !important;
    color: var(--theme-text) !important;
}

.CodeMirror-gutters {
    background-color: var(--theme-mantle) !important;
    border-right: 1px solid var(--theme-border) !important;
}

.CodeMirror-linenumber {
    color: var(--theme-overlay) !important;
}

.CodeMirror-cursor {
    border-left: 2px solid var(--theme-accent) !important;
}

.CodeMirror-selected, pre.CodeMirror-line span.CodeMirror-selectedtext,
::selection {
    background: var(--theme-surface2) !important;
}

/* Syntax Highlighting inside Editor */
.cm-header { color: var(--theme-accent) !important; font-weight: bold !important; }
.cm-header-1 { color: var(--theme-accent) !important; }
.cm-header-2 { color: var(--theme-accent-hover) !important; }
.cm-header-3 { color: var(--theme-accent-muted) !important; }
.cm-url, .cm-link { color: var(--theme-accent) !important; text-decoration: underline !important; }
.cm-quote { color: var(--theme-subtext) !important; font-style: italic !important; }
.cm-comment { color: var(--theme-overlay) !important; }
.cm-keyword { color: var(--theme-accent-hover) !important; }
.cm-variable { color: var(--theme-text) !important; }

/* Code blocks in Editor */
div.CodeMirror div.cm-jn-code-block-background {
    background-color: var(--theme-mantle) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 6px !important;
}

/* Tag Bar & Chips */
.tag-bar, .note-property-box {
    background-color: var(--theme-base) !important;
    border-top: 1px solid var(--theme-border) !important;
}

.tag-list > span, .tag-item, .tag-item-label {
    color: var(--theme-accent) !important;
    background-color: var(--theme-crust) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 4px !important;
    padding: 2px 8px !important;
}

/*********************************************************************************
 * 4. SETTINGS SCREEN (CONFIG SCREEN)
 *********************************************************************************/
.config-screen, div[class*="configScreen"], div[class*="ConfigScreen"],
.config-screen-content, div[class*="config-section"], .settings-page,
div[class*="ConfigScreen"] > div {
    background-color: var(--theme-base) !important;
    color: var(--theme-text) !important;
}

.config-screen .side-bar, div[class*="ConfigScreen"] div[class*="sidebar"],
div[class*="ConfigScreen"] .side-bar {
    background-color: var(--theme-crust) !important;
    border-right: 1px solid var(--theme-border) !important;
}

.config-screen .list-item, div[class*="ConfigScreen"] a,
div[class*="ConfigScreen"] .list-item {
    color: var(--theme-subtext) !important;
    background-color: transparent !important;
}

.config-screen .list-item:hover, div[class*="ConfigScreen"] a:hover {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-text) !important;
}

.config-screen .list-item.selected, div[class*="ConfigScreen"] .selected,
div[class*="ConfigScreen"] [class*="selected"] {
    background-color: var(--theme-accent) !important;
    color: #000000 !important;
    font-weight: 700 !important;
    border-radius: 4px !important;
}
div[class*="ConfigScreen"] [class*="selected"] span,
div[class*="ConfigScreen"] [class*="selected"] div,
div[class*="ConfigScreen"] [class*="selected"] i {
    color: #000000 !important;
    font-weight: 700 !important;
}

/* Settings Form Controls & Checkboxes */
select, input[type="text"], input[type="password"], textarea,
.config-screen select, .config-screen input {
    background-color: var(--theme-surface0) !important;
    border: 1px solid var(--theme-border) !important;
    color: var(--theme-text) !important;
    border-radius: 6px !important;
    padding: 6px 10px !important;
}
select:focus, input:focus {
    border-color: var(--theme-accent) !important;
    outline: none !important;
}

input[type="checkbox"] {
    accent-color: var(--theme-accent) !important;
    width: 16px !important;
    height: 16px !important;
}

/* Settings Action Buttons */
div[class*="ConfigScreen"] button, .config-screen button {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-text) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 6px !important;
    padding: 6px 16px !important;
}
div[class*="ConfigScreen"] button:hover, .config-screen button:hover {
    background-color: var(--theme-accent) !important;
    color: #000000 !important;
    font-weight: 700 !important;
}

/*********************************************************************************
 * 5. MODALS & COMMAND PALETTE
 *********************************************************************************/
div.modal-dialog, .dialog-box, .modal {
    background-color: var(--theme-mantle) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 8px !important;
    box-shadow: 0 12px 36px rgba(0, 0, 0, 0.6) !important;
}

.modal-dialog > div > input {
    background-color: var(--theme-crust) !important;
    color: var(--theme-text) !important;
    border: 1px solid var(--theme-border) !important;
}

.modal-dialog > .item-list div[class="selected"] {
    background-color: var(--theme-surface1) !important;
}

/*********************************************************************************
 * 6. TOP-RIGHT TOOLBAR ICONS (sync, account, layout icons)
 *********************************************************************************/
/* Target the top bar right section and all icon buttons inside it */
div[class*="ToolbarButton"], div[class*="toolbarButton"],
div[class*="topBar"] button, div[class*="TopBar"] button,
.rli-toolbar button, .toolbar button,
div[role="toolbar"] button, div[role="toolbar"] span {
    background-color: transparent !important;
    color: var(--theme-subtext) !important;
    border: none !important;
}
div[class*="ToolbarButton"]:hover, div[class*="toolbarButton"]:hover,
div[class*="topBar"] button:hover, div[role="toolbar"] button:hover {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-accent) !important;
}

/* Icon color fix - SVGs and i tags inside toolbar */
div[class*="topBar"] i, div[class*="TopBar"] i,
div[role="toolbar"] i, .rli-toolbar i,
div[class*="ToolbarButton"] i, div[class*="toolbarButton"] i {
    color: var(--theme-subtext) !important;
}

/*********************************************************************************
 * 7. DROPDOWN / POPUP MENUS (notebook picker, context menus)
 *********************************************************************************/
div[class*="dropdown"], div[class*="Dropdown"],
div[class*="popup"], div[class*="Popup"],
div[class*="menu"], div[class*="Menu"],
ul[role="menu"], div[role="menu"],
div[class*="contextMenu"], div[class*="ContextMenu"] {
    background-color: var(--theme-mantle) !important;
    border: 1px solid var(--theme-border) !important;
    border-radius: 8px !important;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.6) !important;
    color: var(--theme-text) !important;
}

/* Dropdown items */
div[class*="dropdown"] div, div[class*="Dropdown"] div,
ul[role="menu"] li, div[role="menu"] div,
div[class*="menu"] div, div[class*="Menu"] div,
div[class*="contextMenu"] > div, div[class*="ContextMenu"] > div {
    background-color: transparent !important;
    color: var(--theme-text) !important;
}
div[class*="dropdown"] div:hover, ul[role="menu"] li:hover,
div[role="menu"] div:hover, div[class*="menu"] div:hover {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-accent) !important;
}

/* Active/selected notebook in dropdown */
div[class*="dropdown"] div[class*="selected"],
div[class*="dropdown"] div[class*="active"] {
    background-color: var(--theme-surface1) !important;
    color: var(--theme-accent) !important;
    font-weight: 600 !important;
}

/*********************************************************************************
 * 8. NEW NOTE / NEW TO-DO BUTTONS (override Joplin dark theme hardcoded blue)
 *********************************************************************************/
button[class*="new-note"], button[class*="newNote"],
button[class*="new-todo"], button[class*="newTodo"],
div[class*="newNoteButton"], div[class*="newTodoButton"],
.new-note-todo-buttons button {
    background-color: var(--theme-accent) !important;
    color: #000000 !important;
    border: none !important;
    border-radius: 6px !important;
    font-weight: 700 !important;
}
button[class*="new-note"]:hover, button[class*="newNote"]:hover,
button[class*="new-todo"]:hover, button[class*="newTodo"]:hover,
.new-note-todo-buttons button:hover {
    background-color: var(--theme-accent-hover) !important;
    color: #000000 !important;
}
/* Text and icons inside these buttons */
.new-note-todo-buttons button span,
.new-note-todo-buttons button i {
    color: #000000 !important;
}

/*********************************************************************************
 * 9. GLOBAL BUTTON CATCH-ALL (any remaining default blue buttons)
 *********************************************************************************/
/* Catch any button that Joplin's dark theme hardcodes with blue */
button[style*="background-color: rgb(66, 133, 244)"],
button[style*="background-color: #4285f4"],
button[style*="background: rgb(66"],
div[style*="background-color: rgb(66, 133, 244)"] {
    background-color: var(--theme-accent) !important;
    color: #000000 !important;
}

/* Catch inline-styled gray elements */
button[style*="background-color: rgb("],
div[style*="background-color: rgb(45"],
div[style*="background-color: rgb(30"] {
    background-color: var(--theme-surface0) !important;
    color: var(--theme-text) !important;
}
EOF_CHROME


# 2. userstyle.css (Rendered Markdown Notes)
cat << EOF_STYLE > "$JOPLIN_DIR/userstyle.css"
/* ==========================================================================
   Ballade Catppuccin-Grade Rendered Markdown Styling for Joplin
   Auto-generated by Ballade Multi-Theme Orchestrator ($THEME_KEY)
   ========================================================================== */

#rendered-md, body, th, td {
    background-color: $BG_BASE !important;
    color: $FG_TEXT !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;
    line-height: 1.6 !important;
}

h1, h2, h3, h4, h5, h6 {
    color: $ACCENT_HEX !important;
    font-weight: 600 !important;
    margin-top: 1.2em;
    margin-bottom: 0.6em;
}
h1 { border-bottom: 1px solid rgba(255, 255, 255, 0.08); padding-bottom: 0.3em; }
h2 { color: $ACCENT_HOVER !important; border-bottom: 1px solid rgba(255, 255, 255, 0.04); }
h3 { color: $ACCENT_MUTED !important; }

a {
    color: $ACCENT_HEX !important;
    text-decoration: none !important;
}
a:hover {
    color: $ACCENT_HOVER !important;
    text-decoration: underline !important;
}

blockquote {
    border-left: 4px solid $ACCENT_HEX !important;
    background: $SURFACE0 !important;
    padding: 10px 16px !important;
    border-radius: 0 8px 8px 0 !important;
    color: $FG_SUBTEXT !important;
}

code {
    background-color: $SURFACE0 !important;
    color: $ACCENT_HOVER !important;
    padding: 2px 6px !important;
    border-radius: 4px !important;
    border: 1px solid rgba(255, 255, 255, 0.06) !important;
    font-family: "Adwaita Mono", monospace !important;
}

pre, .hljs {
    background-color: $BG_MANTLE !important;
    border: 1px solid rgba(255, 255, 255, 0.08) !important;
    border-radius: 8px !important;
    padding: 12px !important;
    color: $FG_TEXT !important;
}
pre code {
    background-color: transparent !important;
    border: none !important;
    padding: 0 !important;
}

table {
    border-collapse: collapse;
    width: 100%;
}
th, td {
    border: 1px solid rgba(255, 255, 255, 0.08);
    padding: 8px 12px;
}
th {
    background-color: $BG_MANTLE;
    color: $ACCENT_HEX;
}

input[type="checkbox"]:checked {
    accent-color: $ACCENT_HEX !important;
}
EOF_STYLE

echo "[Joplin Themer] Applied Catppuccin-grade $THEME_KEY theme ($ACCENT_HEX) to Joplin."
