#!/usr/bin/env bash
# ==============================================================================
# Ballade Obsidian Dynamic Themer & Frosted Translucency Engine
# Removes hardcoded theme artifacts, provides true frosted glass & crisp text
# ==============================================================================

THEME_KEY="${1:-green}"
VAULT_DIR="$HOME/Notes/Valse de Anshu"
OBSIDIAN_CONFIG="$VAULT_DIR/.obsidian"
SNIPPETS_DIR="$OBSIDIAN_CONFIG/snippets"
SNIPPET_FILE="$SNIPPETS_DIR/ballade-theme.css"
APPEARANCE_FILE="$OBSIDIAN_CONFIG/appearance.json"

[ ! -d "$OBSIDIAN_CONFIG" ] && exit 0
mkdir -p "$SNIPPETS_DIR"

case "$THEME_KEY" in
    green|atelier|everforest)
        ACCENT_HEX="#7D9726"
        ACCENT_HOVER="#93AE38"
        ACCENT_MUTED="#5B9D48"
        BG_PRIMARY="rgba(24, 33, 30, 0.72)"
        BG_SECONDARY="rgba(18, 25, 23, 0.82)"
        BG_ALT="rgba(30, 42, 38, 0.65)"
        TEXT_NORMAL="#E0E6E2"
        TEXT_MUTED="#A2ADA6"
        ;;
    golden|gold|amber|yellow)
        ACCENT_HEX="#F0B849"
        ACCENT_HOVER="#FED268"
        ACCENT_MUTED="#D49B2C"
        BG_PRIMARY="rgba(30, 24, 15, 0.72)"
        BG_SECONDARY="rgba(24, 19, 11, 0.82)"
        BG_ALT="rgba(42, 33, 20, 0.65)"
        TEXT_NORMAL="#EBE4D5"
        TEXT_MUTED="#ADA594"
        ;;
    orange|sunset|tangerine)
        ACCENT_HEX="#FF9248"
        ACCENT_HOVER="#FFB480"
        ACCENT_MUTED="#E0762F"
        BG_PRIMARY="rgba(32, 21, 15, 0.72)"
        BG_SECONDARY="rgba(24, 15, 10, 0.82)"
        BG_ALT="rgba(44, 28, 20, 0.65)"
        TEXT_NORMAL="#EDE2DB"
        TEXT_MUTED="#AEA29A"
        ;;
    pink|sakura)
        ACCENT_HEX="#D4659A"
        ACCENT_HOVER="#F298C4"
        ACCENT_MUTED="#B84E80"
        BG_PRIMARY="rgba(33, 18, 27, 0.72)"
        BG_SECONDARY="rgba(25, 12, 20, 0.82)"
        BG_ALT="rgba(45, 24, 36, 0.65)"
        TEXT_NORMAL="#EFE0E8"
        TEXT_MUTED="#AFA0A8"
        ;;
    purple|amethyst)
        ACCENT_HEX="#9C5ADB"
        ACCENT_HOVER="#BA68C8"
        ACCENT_MUTED="#7B3EA6"
        BG_PRIMARY="rgba(26, 18, 35, 0.72)"
        BG_SECONDARY="rgba(20, 13, 28, 0.82)"
        BG_ALT="rgba(36, 24, 48, 0.65)"
        TEXT_NORMAL="#E7E0EF"
        TEXT_MUTED="#A7A0AF"
        ;;
    red|crimson)
        ACCENT_HEX="#BF3F43"
        ACCENT_HOVER="#E55353"
        ACCENT_MUTED="#A32E32"
        BG_PRIMARY="rgba(33, 16, 18, 0.72)"
        BG_SECONDARY="rgba(25, 10, 12, 0.82)"
        BG_ALT="rgba(45, 20, 23, 0.65)"
        TEXT_NORMAL="#EFE0E1"
        TEXT_MUTED="#AFA0A1"
        ;;
    blue|tokyo_night|tokyonight)
        ACCENT_HEX="#7AA2F7"
        ACCENT_HOVER="#89B4FA"
        ACCENT_MUTED="#5C7EB5"
        BG_PRIMARY="rgba(21, 22, 30, 0.72)"
        BG_SECONDARY="rgba(15, 16, 23, 0.82)"
        BG_ALT="rgba(29, 31, 42, 0.65)"
        TEXT_NORMAL="#E0E4F0"
        TEXT_MUTED="#A0A5B5"
        ;;
    grayscale|nord|monochrome|bw)
        ACCENT_HEX="#88C0D0"
        ACCENT_HOVER="#81A1C1"
        ACCENT_MUTED="#5E81AC"
        BG_PRIMARY="rgba(30, 34, 42, 0.72)"
        BG_SECONDARY="rgba(23, 26, 32, 0.82)"
        BG_ALT="rgba(40, 45, 56, 0.65)"
        TEXT_NORMAL="#E5E9F0"
        TEXT_MUTED="#A5A9B5"
        ;;
    *)
        ACCENT_HEX="#7D9726"
        ACCENT_HOVER="#93AE38"
        ACCENT_MUTED="#5B9D48"
        BG_PRIMARY="rgba(24, 33, 30, 0.72)"
        BG_SECONDARY="rgba(18, 25, 23, 0.82)"
        BG_ALT="rgba(30, 42, 38, 0.65)"
        TEXT_NORMAL="#E0E6E2"
        TEXT_MUTED="#A2ADA6"
        ;;
esac

cat << EOF_CSS > "$SNIPPET_FILE"
/* ==========================================================================
   Ballade Translucent Frosted Glass Theme Engine for Obsidian
   Auto-generated by Ballade Multi-Theme Orchestrator ($THEME_KEY)
   ========================================================================== */

/* 1. OVERRIDE & KILL HARDCODED BASE64 GREEN BACKGROUND ARTIFACTS */
body::before,
body.bg-auto.theme-dark::before,
body.bg-auto.theme-light::before,
body.theme-dark::before,
.app-container::before {
    background-image: none !important;
    background-color: transparent !important;
    display: none !important;
}

/* 2. ROOT THEME VARIABLES */
.theme-dark, .theme-light, :root {
    --accent-color: $ACCENT_HEX !important;
    --text-accent: $ACCENT_HEX !important;
    --text-accent-hover: $ACCENT_HOVER !important;
    --interactive-accent: $ACCENT_HEX !important;
    --interactive-accent-hover: $ACCENT_HOVER !important;
    --interactive-accent-rgb: $(printf "%d, %d, %d" 0x${ACCENT_HEX:1:2} 0x${ACCENT_HEX:3:2} 0x${ACCENT_HEX:5:2}) !important;

    /* Crisp Typography */
    --text-normal: $TEXT_NORMAL !important;
    --text-muted: $TEXT_MUTED !important;
    --text-faint: rgba(255, 255, 255, 0.35) !important;
    --link-color: $ACCENT_HEX !important;
    --link-color-hover: $ACCENT_HOVER !important;
    --link-external-color: $ACCENT_HOVER !important;
    
    /* Pure Frosted Glass Translucency */
    --background-primary: $BG_PRIMARY !important;
    --background-primary-alt: $BG_ALT !important;
    --background-secondary: $BG_SECONDARY !important;
    --background-secondary-alt: $BG_ALT !important;
    --background-modifier-border: rgba(255, 255, 255, 0.08) !important;
    --background-modifier-border-hover: rgba(255, 255, 255, 0.16) !important;
    --background-modifier-border-focus: $ACCENT_HEX !important;
    --background-modifier-hover: rgba(255, 255, 255, 0.06) !important;
    --background-modifier-active-hover: rgba(255, 255, 255, 0.10) !important;
    
    /* Titlebar & Sidebars */
    --titlebar-background: transparent !important;
    --titlebar-background-focused: transparent !important;
    --tab-background-active: rgba(255, 255, 255, 0.08) !important;
    --nav-item-color-active: $ACCENT_HEX !important;
    --nav-item-background-active: rgba(255, 255, 255, 0.08) !important;
    --nav-item-color-hover: $TEXT_NORMAL !important;
    
    /* Headings (Crisp & Themed) */
    --h1-color: $ACCENT_HEX !important;
    --h2-color: $ACCENT_HOVER !important;
    --h3-color: $ACCENT_MUTED !important;
    --h4-color: $ACCENT_HEX !important;
    --h5-color: $ACCENT_HOVER !important;
    --h6-color: $ACCENT_MUTED !important;
    
    /* Checkboxes, Tags, Cursors & Selection */
    --caret-color: $ACCENT_HEX !important;
    --text-selection: rgba(255, 255, 255, 0.20) !important;
    --text-highlight-bg: rgba(255, 255, 255, 0.15) !important;
    --checkbox-color: $ACCENT_HEX !important;
    --checkbox-color-hover: $ACCENT_HOVER !important;
    --tag-color: $ACCENT_HEX !important;
    --tag-background: rgba(255, 255, 255, 0.06) !important;
    --tag-background-hover: rgba(255, 255, 255, 0.12) !important;
    --tag-border-color: rgba(255, 255, 255, 0.10) !important;
}

/* 3. WINDOW & CONTAINER GLASS EFFECT */
body, .app-container, .horizontal-main-container, .workspace {
    background-color: $BG_PRIMARY !important;
    backdrop-filter: blur(16px);
}

.workspace-leaf, .workspace-split {
    background-color: transparent !important;
}

/* 4. ACTIVE FILE / TREE VIEW ACCENT */
.nav-file-title.is-active, .nav-folder-title.is-active {
    background-color: rgba(255, 255, 255, 0.08) !important;
    color: $ACCENT_HEX !important;
    border-left: 3px solid $ACCENT_HEX !important;
}

/* 5. CODE BLOCKS & CALLOUTS */
.cm-s-obsidian pre.HyperMD-codeblock, .markdown-rendered pre {
    background-color: rgba(0, 0, 0, 0.35) !important;
    border: 1px solid rgba(255, 255, 255, 0.08) !important;
    border-radius: 8px !important;
}
.callout {
    border-left: 4px solid $ACCENT_HEX !important;
    background-color: rgba(255, 255, 255, 0.04) !important;
}

/* 6. MODALS, POPOVERS & MENUS */
.modal, .popover, .menu, .suggestion-container {
    background-color: $BG_SECONDARY !important;
    border: 1px solid rgba(255, 255, 255, 0.12) !important;
    border-radius: 12px !important;
    box-shadow: 0 12px 36px rgba(0, 0, 0, 0.45) !important;
}
EOF_CSS

if [ -f "$APPEARANCE_FILE" ]; then
    tmp_json=$(mktemp)
    jq --arg accent "$ACCENT_HEX" '
        .accentColor = $accent |
        .enabledCssSnippets = ((.enabledCssSnippets // []) + ["ballade-theme"] | unique)
    ' "$APPEARANCE_FILE" > "$tmp_json" && mv "$tmp_json" "$APPEARANCE_FILE"
fi

echo "[Obsidian Themer] Applied $THEME_KEY theme ($ACCENT_HEX) to Obsidian."
