# Amethyst / Cyberpunk Purple Kitty Theme
background #14101a
foreground #ede7f6
selection_background #443c68
selection_foreground #ffffff
cursor #ba68c8
cursor_text_color #14101a

# Normal colors
color0 #221b2b
color1 #ff5252
color2 #4dd0e1
color3 #ffca28
color4 #9c27b0
color5 #e040fb
color6 #ce93d8
color7 #ede7f6

# Bright colors
color8 #473559
color9 #ff1744
color10 #80cbc4
color11 #ffe082
color12 #ab47bc
color13 #ea80fc
color14 #e1bee7
color15 #ffffff

