# Crimson / Scarlet Red Kitty Theme
background #181012
foreground #ffeaec
selection_background #5c1d22
selection_foreground #ffffff
cursor #ef5350
cursor_text_color #181012

# Normal colors
color0 #261619
color1 #ff1744
color2 #4caf50
color3 #ffb74d
color4 #d32f2f
color5 #c2185b
color6 #ff8a80
color7 #ffeaec

# Bright colors
color8 #522d32
color9 #ff5252
color10 #69f0ae
color11 #ffd54f
color12 #ef5350
color13 #e91e63
color14 #ffab91
color15 #ffffff

