#!/usr/bin/env bash
set -euo pipefail

# 1. Play crisp chime immediately so user gets zero-latency sound feedback
paplay --volume=65536 /usr/share/sounds/freedesktop/stereo/bell.oga 2>/dev/null || pw-play /usr/share/sounds/freedesktop/stereo/bell.oga 2>/dev/null || true &

# Find primary / focused monitor
MONITORS_JSON="$(hyprctl monitors -j)"
MON_NAME="$(echo "$MONITORS_JSON" | jq -r '(.[] | select(.focused == true) | .name) // (.[0].name) // "eDP-1"')"
CURRENT_HZ="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .refreshRate) // 144")"
WIDTH="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .width) // 1920")"
HEIGHT="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .height) // 1080")"
SCALE="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .scale) // 1")"
POS_X="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .x) // 0")"
POS_Y="$(echo "$MONITORS_JSON" | jq -r "(.[] | select(.name == \"$MON_NAME\") | .y) // 0")"

# Round or parse float
IS_HIGH=$(awk -v hz="$CURRENT_HZ" 'BEGIN { print (hz > 90.0) ? 1 : 0 }')

if [ "$IS_HIGH" -eq 1 ]; then
    TARGET_HZ="60.00Hz"
    TARGET_LABEL="60"
    TARGET_DESC="60 Hz (Standard • Power Saving)"
else
    TARGET_HZ="144.00Hz"
    TARGET_LABEL="144"
    TARGET_DESC="144 Hz (Ultra Smooth • Gaming)"
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Switching $MON_NAME from ${CURRENT_HZ}Hz to $TARGET_HZ"

# 2. Apply dynamically in Hyprland
hyprctl eval "hl.monitor({ output = \"$MON_NAME\", mode = \"${WIDTH}x${HEIGHT}@$TARGET_HZ\", position = \"${POS_X}x${POS_Y}\", scale = $SCALE })"

# 3. Persist in monitors.lua so it survives reloads / reboots
MONITORS_LUA="$HOME/.config/hypr/monitors.lua"
cat <<EOF > "$MONITORS_LUA"
-- Generated by toggle_refresh_rate.sh
hl.monitor({
    output = "$MON_NAME",
    mode = "${WIDTH}x${HEIGHT}@$TARGET_HZ",
    position = "${POS_X}x${POS_Y}",
    scale = $SCALE
})
EOF

# 4. Log to system log & local log
logger -t hypr-refresh "Switched $MON_NAME to $TARGET_HZ"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Switched $MON_NAME to $TARGET_HZ" >> "$HOME/.config/hypr/refresh_rate.log"

# 5. Trigger QuickShell On-Screen Feedback HUD (bottom middle) & sync monitor info
qs -c ballade ipc call feedbackHud showRefreshRate "$TARGET_LABEL" 2>/dev/null || true
